### ISSUE TITLE
OnBackPressed with the version Beta01 doesn't work as intended

### ISSUE THREAD

**Issue by eminuluyol** [moallemi/MultiNavHost#2]
If you update the Navigation Component version to Beta01, you will see that the `oBackPressed` doesn't work as intended. You need to double click on it for popping up the fragment and also it is causing crash

**Comment by moallemi** [comment]
Please take a look at https://github.com/moallemi/MultiNavHost/commit/7f8d52c8ca707e2956a60c51e331175556f375ba. It is now working with 1.0.0-beta01
